# wget https://api.github.com/repos/nixos/nix/issues?page=1
# wget https://api.github.com/repos/nixos/nix/issues?page=2
# wget https://api.github.com/repos/nixos/nix/issues?page=3
# wget https://api.github.com/repos/nixos/nix/issues?page=4
# wget https://api.github.com/repos/nixos/nix/issues?page=5
# wget https://api.github.com/repos/nixos/nix/issues?page=6
# wget https://api.github.com/repos/nixos/nix/issues?page=7
# wget https://api.github.com/repos/nixos/nix/issues?page=8
# wget https://api.github.com/repos/nixos/nix/issues?page=9
# wget https://api.github.com/repos/nixos/nix/issues?page=10
# wget https://api.github.com/repos/nixos/nix/issues?page=11
# wget https://api.github.com/repos/nixos/nix/issues?page=12
# wget https://api.github.com/repos/nixos/nix/issues?page=13
# wget https://api.github.com/repos/nixos/nix/issues?page=14
# wget https://api.github.com/repos/nixos/nix/issues?page=15
# wget https://api.github.com/repos/nixos/nix/issues?page=16
# wget https://api.github.com/repos/nixos/nix/issues?page=17
# wget https://api.github.com/repos/nixos/nix/issues?page=18
# wget https://api.github.com/repos/nixos/nix/issues?page=19
# wget https://api.github.com/repos/nixos/nix/issues?page=10
# wget https://api.github.com/repos/nixos/nix/issues?page=21
# wget https://api.github.com/repos/nixos/nix/issues?page=22
# wget https://api.github.com/repos/nixos/nix/issues?page=23
# wget https://api.github.com/repos/nixos/nix/issues?page=24
# wget https://api.github.com/repos/nixos/nix/issues?page=25
# wget https://api.github.com/repos/nixos/nix/issues?page=26
# wget https://api.github.com/repos/nixos/nix/issues?page=27
# wget https://api.github.com/repos/nixos/nix/issues?page=28
# wget https://api.github.com/repos/nixos/nix/issues?page=29
# wget https://api.github.com/repos/nixos/nix/issues?page=30
# wget https://api.github.com/repos/nixos/nix/issues?page=31
# wget https://api.github.com/repos/nixos/nix/issues?page=32
# wget https://api.github.com/repos/nixos/nix/issues?page=33
# wget https://api.github.com/repos/nixos/nix/issues?page=34
wget https://api.github.com/repos/nixos/nix/issues?page=35
wget https://api.github.com/repos/nixos/nix/issues?page=36
wget https://api.github.com/repos/nixos/nix/issues?page=37
wget https://api.github.com/repos/nixos/nix/issues?page=38
wget https://api.github.com/repos/nixos/nix/issues?page=39
wget https://api.github.com/repos/nixos/nix/issues?page=40
wget https://api.github.com/repos/nixos/nix/issues?page=41
wget https://api.github.com/repos/nixos/nix/issues?page=42
wget https://api.github.com/repos/nixos/nix/issues?page=43
wget https://api.github.com/repos/nixos/nix/issues?page=44
wget https://api.github.com/repos/nixos/nix/issues?page=45
wget https://api.github.com/repos/nixos/nix/issues?page=46
wget https://api.github.com/repos/nixos/nix/issues?page=47
wget https://api.github.com/repos/nixos/nix/issues?page=48
wget https://api.github.com/repos/nixos/nix/issues?page=49
wget https://api.github.com/repos/nixos/nix/issues?page=50
wget https://api.github.com/repos/nixos/nix/issues?page=51
wget https://api.github.com/repos/nixos/nix/issues?page=52
wget https://api.github.com/repos/nixos/nix/issues?page=53
wget https://api.github.com/repos/nixos/nix/issues?page=54
wget https://api.github.com/repos/nixos/nix/issues?page=55
wget https://api.github.com/repos/nixos/nix/issues?page=56
wget https://api.github.com/repos/nixos/nix/issues?page=57
wget https://api.github.com/repos/nixos/nix/issues?page=58
wget https://api.github.com/repos/nixos/nix/issues?page=59
wget https://api.github.com/repos/nixos/nix/issues?page=60
wget https://api.github.com/repos/nixos/nix/issues?page=61
wget https://api.github.com/repos/nixos/nix/issues?page=62
wget https://api.github.com/repos/nixos/nix/issues?page=63
wget https://api.github.com/repos/nixos/nix/issues?page=64
wget https://api.github.com/repos/nixos/nix/issues?page=65
wget https://api.github.com/repos/nixos/nix/issues?page=66
wget https://api.github.com/repos/nixos/nix/issues?page=67
wget https://api.github.com/repos/nixos/nix/issues?page=68
wget https://api.github.com/repos/nixos/nix/issues?page=69
wget https://api.github.com/repos/nixos/nix/issues?page=70
wget https://api.github.com/repos/nixos/nix/issues?page=71
wget https://api.github.com/repos/nixos/nix/issues?page=72
wget https://api.github.com/repos/nixos/nix/issues?page=73
wget https://api.github.com/repos/nixos/nix/issues?page=74
